// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDunoUt8NaIAyTIhbHMqKlRjw5Zmri3k9g',
    appId: '1:1052833022709:web:8696c069e79fa2650c7bbc',
    messagingSenderId: '1052833022709',
    projectId: 'kasir-app-d87b1',
    authDomain: 'kasir-app-d87b1.firebaseapp.com',
    storageBucket: 'kasir-app-d87b1.appspot.com',
    measurementId: 'G-4B8LQ8VC7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJb1F7IWBeUaqtwYVU41ivh1XRB46VDRk',
    appId: '1:1052833022709:android:c07cd1db111af91c0c7bbc',
    messagingSenderId: '1052833022709',
    projectId: 'kasir-app-d87b1',
    storageBucket: 'kasir-app-d87b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT_ExC3CZQro4mtvkvcqCvZioLRsPk67M',
    appId: '1:1052833022709:ios:3d0d3cfbff79f01b0c7bbc',
    messagingSenderId: '1052833022709',
    projectId: 'kasir-app-d87b1',
    storageBucket: 'kasir-app-d87b1.appspot.com',
    iosClientId: '1052833022709-o25ko676e50sv3cv9rgpbj5uv1u5kpih.apps.googleusercontent.com',
    iosBundleId: 'in.ryzntx.cashier',
  );
}
